server:
  port: 8888

spring:
  application:
    name: my-demo
  jackson:
    timeZone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss:SSS
    default-property-inclusion: non_null
    parser:
      allow-single-quotes: true
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:18103/zyhl?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&autoReconnect=true&useSSL=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      pool-name: DatebookHikariCP
      max-lifetime: 180000
      idle-timeout: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 1
    host: 127.0.0.1
    port: 18130
    password:
    timeout: 1000
    pool:
      max-active: 20
      max-wait: -1
      max-idle: 10
      min-idle: 1

mybatis-plus:
#  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-statement-timeout: 3 # 查询超时间,单位秒,不设置则无线等待
    default-fetch-size: 100
    map-underscore-to-camel-case: true
  type-aliases-package: org.example.entity